version: '2'
services:
 zabbix-agent:
  image: zabbix/zabbix-agent:alpine-4.0-latest
  ports:
   - "10050:10050"
  volumes:
   - etc_zabbix_zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - var_lib_zabbix_modules:/var/lib/zabbix/modules:ro
   - var_lib_zabbix_enc:/var/lib/zabbix/enc:ro
   - var_lib_zabbix_ssh_keys:/var/lib/zabbix/ssh_keys:ro
  env_file:
   - env_timezone
   - env_agent
  user: root
  privileged: true

volumes:
  etc_zabbix_zabbix_agentd.d:
  var_lib_zabbix_modules:
  var_lib_zabbix_enc:
  var_lib_zabbix_ssh_keys:
